CREATE TABLE `HostedInstanceTrial` (
 `id` INTEGER NOT NULL DEFAULT 1,
 `startedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
